name: anime_face_tracker
channels:
 - conda-forge
 - anaconda
dependencies:
 - python=3.8
 - python-mss
 - opencv=4.5.0
 - matplotlib
 - jupyterlab
 - pip:
   - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.4.0-cp38-cp38-manylinux2010_x86_64.whl
